### ISSUE TITLE
CEDAR: sources for geographic terms

### ISSUE THREAD

**Issue by eslao** [LD4P/requirements#176]
Is “GAZ” the best resource to use? (Gazetteer, https://www.ebi.ac.uk/ols/ontologies/gaz; from the European Bioinformatics Institute). This ontology may be appropriate for the researchers using CEDAR, but is it appropriate for users outside the original intended audience? If CEDAR is slanted towards bioinformatics, according to its original purpose, is it the best editor for more general use?

**Comment by graybeal** [comment]
The ontology(ies) that is (are) chosen for a template are chosen by the template developer. CEDAR was not built to be slanted toward bioinformatics, and there is no limit on what kind of ontology is put into BioPortal, which is likewise technologically neutral. 

As an alternative, it is possible to set up a dedicated CEDAR and a dedicated BioPortal (n.b. 
http://biblio.ontoportal.org) if the community wants a fully dedicated system.

**Comment by NancyL** [comment]
I only used GAZ because at the moment we do not have access to NAF or LCSH through BioPortal--these are more likely to lookups rather than downloads because of their size and dynamics. I did say in the intro session that this was not what anyone would use for cataloging purposes, but was there just to provide some data.

**Comment by michelleif** [comment]
Sinopia offers NAF and LCSH
