### ISSUE TITLE
Need better way to enter diacritics and special characters

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/requirements#184]
Currently in Sinopia, there is no good way to enter the diacritics used in multiple Latin script languages as well as in transliterating non-Latin script. The method of using the alt key with 4-digit codes is extremely difficult and slow. In addition this method only support characters used in West European languages; the combinations for diacritics used in some East European languages, etc. lack an alt key combination. For people working with multiple languages picking and using the various foreign keyboards in Windows is not realistic. There needs to be a way to enter diacritics and special characters in Sinopia a manner similar to the way catalogers now do this in OCLC Connexion Client (and in ILSs). In Connexion Client, catalogers can use the Enter Diacritics and Special Characters table or they can use keyboard shortcuts (e.g. <Ctrl><Alt><b> will enter an acute accent over a letter).

**Comment by michelleif** [comment]
adding some additional info here since this has come up again as an important requirement:

from #116 :
--the developer of MarcEdit experimented with adding this keyboard: https://www.lexilogos.com/keyboard/

--info from catalogers at Stanford on how they currently work with diacritics and non-Roman characters in OCLC Connexion.

**Diacritics**: preferred method (given available methods) is to type the roman letter, and then open a pop-up window (or palette) showing relevant diacritical marks, and choose the one you want. There are "palettes" for each language, so choose the appropriate language and then you see only the appropriate marks. This method is easier than entering numeric codes. Some still use a special RLIN keyboard which you can download via OCLC. There are keyboard shortcuts to bring up these palettes (and catalogers can define their own keyboard shortcuts)

**non-Roman script**, two methods:
(1) type in the text transliterated to roman script. Run the incorporated transliterator to turn it into desired non-Roman language. The advantage of this method (over method 2 below) is that you can use the roman keyboard all the time and don't have to switch. Note that this method does not work properly for Hebrew.
The transliterator incorporated into OCLC is found here:
http://www.hahnlibrary.net/libraries/oml/connex.html
see "Transliteration"
it is not maintained by OCLC
(2) set up your machine to have additional keyboard mapping options. then switch back and forth between non-roman and roman keyboard mappings.

**Comment by michelleif** [comment]
see @jermnelson for latest requirements and description of work to be attempted in Work Cycle 2

**Comment by michelleif** [comment]
closed by https://github.com/LD4P/sinopia_editor/pull/1873
