### ISSUE TITLE
LC Editor: Clogged with fields which seem repetitive [person’s role as opposed to relationship designator], yet not enough fields for useful information [variations in title]

### ISSUE THREAD

**Issue by pmgreen** [LD4P/requirements#69]

**Comment by michelleif** [comment]
see also #20

**Comment by michelleif** [comment]
part of this may be a template configuration issue--if the template was changed to include more useful fields and eliminate repetitive fields would that help? or is it a question of the cataloger being able to easily create their own template based on a standard template, in order to remove fields not relevant to them? or ability of cataloger to hide some less essential fields?
